//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketRespons
    {
        public int TicketResponseId { get; set; }
        public string QuestionText { get; set; }
        public string Response { get; set; }
    
        public virtual TicketRespons TicketResponses1 { get; set; }
        public virtual TicketRespons TicketRespons1 { get; set; }
    }
}
